name = "localpdfly"
main = "worker/index.ts"
compatibility_date = "2026-02-11"
node_compat = true

[build]
command = "npm run build"
pages_build_output_dir = "dist"

[[r2_buckets]]
binding = "PDF_BUCKET"
bucket_name = "localpdfly-temp"
